version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5

jobs:
  codecov-generate-upload:
    description: Generate JaCoCo coverage and upload on Codecov
    executor: << parameters.executor >>
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: gradle/gradle
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: JaCoCo Test Report
                command: ./gradlew jacocoTestReport
      - codecov/upload:
          file: build/reports/jacoco/report.xml

workflows:
  backend:
    jobs:
      - gradle/test:
          name: JUnit
          test_results_path: build/test-results
          reports_path: build/reports
      - gradle/run:
          name: ktlint
          command: ktlintCheck
      - codecov-generate-upload:
          name: Codecov
          requires:
            - JUnit
